# Generated by Django 3.0.8 on 2020-07-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 15, 30, 8, 347999)),
            preserve_default=False,
        ),
    ]
