# Generated by Django 3.0.8 on 2020-07-03 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 7, 3, 15, 47, 36, 44540), unique=True),
            preserve_default=False,
        ),
    ]
