# Generated by Django 3.0.8 on 2020-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.IntegerField(),
        ),
    ]
